### ISSUE TITLE
env variables not substituted on deploy -f

### ISSUE THREAD

**Issue by karticus** [svdgraaf/serverless-pseudo-parameters#15]
Forgive me, I'm a bit new to the serverless platform.

I'm trying to send asw pseudo params as environment variables into my lambda functions so I can construct arns in there for publishing to sns.   I have config like:
```
provider:
    ...
    environment:
        AWS_ACCOUNT_ID: '#{AWS::AccountId}'
```
upon `sls deploy` everything works great.
If I subsequently `sls deploy -f myFcn`, the pseudo params are not substituted but are in fact overwritten. In the aws console, the value of the env variables is the unsubstituted string '#{AWS::AccountId}'.  Then even a full deploy won't reset the env vars and I have to `sls remove` and `sls deploy` to get the env vars to reset.   

Is this me just not understanding the sls lifecycle with regard to deploy -f? or is there some way to get the plugin to substitute the vars for function deploys.

**Comment by c-anna** [comment]
Exactly the same thing is happening to me. +1!

**Comment by levischuckeats** [comment]
Happened here too.

I was able to reverse this by temporarily removing the environmental variables and then putting them back with a few deploys.

Due to stored data in S3, I can't tear down the whole thing with sis remove.

**Comment by svdgraaf** [comment]
I see the problem, it probably does have to do with the level where the plugin attaches. If someone can lend a hand with a PR, that is more than welcome

**Comment by keithburrows** [comment]
Hi,
I am a completely new to node so no chance of me fixing of this.  However maybe what I have found out may help...

I had recently been given a new laptop so built everything from scratch, which included serverless version 1.29.1.  

And I had the issue described here.

On my old laptop I had the 1.24.1 and I was not getting the issue.  Anyhow I have rolled back serverless to 1.24.1 on my new laptop and the problem is now resolved.  Clearly this is not ideal, but it allows me to continue...

ta

**Comment by imjaroiswebdev** [comment]
@karticus @svdgraaf This solution is working great for me:

define the pseudo parameter(s) as a property in the custom field of your `serverless.yml` file and there add the template for inserting the pseudo parameter with this plugin, then call the custom property in your environment variables. Like this...

```
# serverless.yml
...
custom:
  accountId: "#{AWS::AccountId}"
...
provider:
  environment:
    ACCOUNT_ID: ${self:custom.accountId}
```

**Comment by dmarreco** [comment]
upvote +1 o/

will try to take a look into it in moment, maybe i can help.

**Comment by girwin** [comment]
I'm not sure there's an easy solution for this ... I tried getting replacement of things like `#{AWS::AccountId}` to work on function deploy but discovered what seems like a blocking problem. When you run `serverless deploy --function <your function>` it doesn't seem to process the cloud formation template. Instead it pushes the code and issues commands to update the environment. I registered a hook on `before:deploy:function:deploy` and it executes fine, can change the values of the environment for the function, but the problem is things like ${AWS::AccountId} do not get replaced because they are not processed by CloudFormation.

**Comment by keithburrows** [comment]
At a best guess, the problem introduced during this issue fix https://github.com/serverless/serverless/pull/4173 where by the sls -f parameter had its default change to additionally update the environment variables.  As this does not use the standard cloudFormation deployment I cant see where you add the pseudoParameter code.

What I have done on my local machine is commented out update of environment variables within the serverless framework for a function only deployment.

IMHO The ideal fix is to have another option within the serverless framework i.e. sls -fc "functionCode" only.

**Comment by eclipse1985** [comment]
Same problem here, any news?

**Comment by cscetbon** [comment]
Same here. Would be great to have it fixed ...

**Comment by svdgraaf** [comment]
Seeing as the command in question does a `updateFunctionConfiguration` (see: https://github.com/serverless/serverless/pull/4173/files#diff-4cbb6c3b54085f7b84b5aea9b859bb1eR141) and completely bypasses cloudformation, there is no way to use cloudformation pseudo parameters in that way.

I addition to this. If the value was changed manually through the api call, CF will not see any changes, and will happily skip over the changes you deployed manually. There is no way to fix this if you are doing this outside of cloudformation.

I recommend you do not use the inline updater and always do a full deploy for any changes.

**Comment by cscetbon** [comment]
I'm going to create an issue on Serverless and see what they say. They might accept to add a parameter to that function to not skip the CloudFormation step.
> ... if the value was changed manually ...

What do you mean ? which one ?

In the meantime I think it should be documented somewhere.

**Comment by gudata** [comment]
the same when using "invoke local"
