### ISSUE TITLE
Pseudo parameters do not work on provider.deploymentBucket string

### ISSUE THREAD

**Issue by jacintoArias** [svdgraaf/serverless-pseudo-parameters#16]
Sorry if this is an intended or unavoidable effect, I have not gone through the source code of the plugin.

I have a particular use case in which I wish to set a custom `deploymentBucket` for my service whose name depends on the `AWS::AccountId` parameter.

```
provider:
  deploymentBucket: mydeploymentbucketname-#{AWS::AccountId}
```

However it seems that serverless is checking the validity of the string before the pseudo parameter substitution, throwing the following error:

```
Bucket name must end with a letter or number. mydeploymentbucketname-#{AWS::AccountId}
```

**Comment by jacintoArias** [comment]
Update: It seems that this does not work in any configuration string that does not translate into CF. 

As I said I am blindly talking here, but perhaps as this steps are pre-stack-creation we dont  have access to this parameters... Is that right?

**Comment by svdgraaf** [comment]
The "problem" here is those configs can (or should?) be strings/arrays, this plugin translates them into Ref's/Sub's for CloudFormation. So yes, it's not so much a problem with the plugin, but in the way the framework uses CloudFormation.

I *think* there might be a solution where we take the fully generated json template (right before the CloudFormation update is being run), and replace all the variables there into Ref's/Sub's. I'll mark this as a feature request, there are more people having this issue.

**Comment by gillisda** [comment]
The framework seems to impose inappropriate validations such as length<63 and no caps, no special characters.

**Comment by svdgraaf** [comment]
Hmmm, I've looked into this a bit. The "problem" is that the framework does not give any control over the initial "create-stack" template. In this template the `ServerlessDeploymentBucket` bucket is created, without a property "name". This means that CloudFormation will generate one (based on the stack name and some random things). This is great for uniqueness, not so much for control.

However, there is a workaround.

The framework does allow you to set resources in the `resources` section, which gets merged into the cloudformation template, and which overrides the generated resource, like so:

```
resources:
  Resources:
    ServerlessDeploymentBucket:
      DeletionPolicy: Retain
      Type: AWS::S3::Bucket
      Properties:
        BucketName: my-test-#{AWS::AccountId}-#{AWS::Region}
```

It's the easiest if you can do this on the first creation of the stack. Also, don't upload *ANY* functions while you do this the first time (comment them all out). Subsequent deploys are fine of course. The framework uploads files to whichever is the bucket name when the deploy starts. So any lambda code will be uploaded in the initial created bucket when you deploy the first time. On the second deploy, it will upload them into the new bucket.

If you need to do this on an existing template, you will have to disable any lambda functions that you have for one deploy to override this bucket. Again, the framework will upload all the application code into your old bucket, while it is creating your new bucket. The next deploy you can enable all functions again, and all code will be uploaded in the new created bucket.

Also, you will have to remove the (old) bucket manually, as cloudformation can not delete any buckets with files in it (rightfully so), so that's a manual step you have to take.

All in all: if you are starting a new stack, this is pretty easy, if you have a running stack, this will be a bit of work, but definitely doable.

I hope this workaround helps.

**Comment by cursedcoder** [comment]
Anything listed under Resources will be managed by serverless and make it impossible to use across several accounts (s3 buckets should be unique).
So, the suggested workaround is not a workaround at all.

The real workaround – define a new serverless plugin:
```js
async function retrieveIdentity() {
  const STS = new aws.STS();

  return await STS.getCallerIdentity().promise();
}

module.exports = function deployer(sls, options) {
  instance.hooks['package:cleanup'] = async () => {
    const identity = await retrieveIdentity();
    sls.service.provider.deploymentBucket = `tcp-serverless-${identity.Account}`;

    proxySls.service.provider.deploymentBucketObject = {
      name: `tcp-serverless-${identity.Account}`,
      serverSideEncryption: 'AES256',
      maxPreviousDeploymentArtifacts: 10,
    };
  };

  return this;
};

```
