### ISSUE TITLE
Pseudo parameters not working for custom variables or resources

### ISSUE THREAD

**Issue by jfoxtech** [svdgraaf/serverless-pseudo-parameters#25]
We are using v. `2.2.0`, and apparently, the issue reported in #10 has returned:

Serverless file snippet:

```
custom:
  ...
  email_queue_url: "arn:aws:sqs:us-east-1:#{AWS::AccountID}:${self:custom.email_queue_name}"
```
```
functions:
    ...
    environment:
      ...
      ASSEMBLER_QUEUE_URL: "${self:custom.email_queue_url}"
```

**Comment by svdgraaf** [comment]
For anyone who wants to work on this. I think the plugin should attach at a earlier (or later) step in deploy process. Not sure which one.

I guess the order of lifecycle events has changed in a more recent version of SLS again?

https://gist.github.com/HyperBrain/50d38027a8f57778d5b0f135d80ea406

**Comment by master-of-null** [comment]
+1

**Comment by svdgraaf** [comment]
Where are you having this issue? I can't reproduce it over here. Do you have an example input and output that is generated?

**Comment by master-of-null** [comment]
If I try to reference a resource that's in a different service: 

```
environment:
  event_topic: arn:aws:sns:#{AWS::Region}:#{AWS::AccountId}:${self:custom.event_topic}

```
But it's weird because it will work sometimes

**Comment by bmccann36** [comment]
the fact that it works sometimes makes me wonder if it is the following:
are you getting the error 
`Serverless plugin "serverless-pseudo-parameters" initialization errored: Cannot read property 'pseudoParameters' of null` ?
I have gotten stuck on this error for a while on more than one occasion and it turns out to be a problem with my sls.yml file syntax
for example, in the process of debugging a problem where sls package fails to output a cloudformation template I will comment lines within the 'custom:' section
for example 
`
custom:       
'/* my commented out code */ '
` 
when you do this the serverless-pseudo-param plugin fails
however without the plugin serverless will still work
I suspect that if you declare most other sections of the sls.yml template but leave their contents blank you will encounter the same issue

**Comment by medikoo** [comment]
Closing, as all functionalities as provided by this plugin are now covered by the Framework (since v2.50.0)
